apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgdb
spec:
  selector:
    matchLabels:
      app: pgdb
  template:
    metadata:
      labels:
        app: pgdb
    spec:
      containers:
      - name: pgdb
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: a
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
