version: '3.1'
services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: a
    ports:
      - 5000:5432
    volumes:
      - data:/var/lib/postgresql/data

  web:
    image: darshanusha2/docker-spring
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    depends_on: 
      - pgdb

volumes:
  data: